version: '3.4'

services:
  vouchersystem.voucherfileprocessor:
    image: ${DOCKER_REGISTRY-}vouchersystemvoucherfileprocessor
    build:
      context: .
      dockerfile: VoucherSystem.VoucherFileProcessor/Dockerfile
    volumes:
        - ./VoucherSystem.VoucherFileProcessor/Vouchers:/app/storage
    links:
        - redis_service
    depends_on:
        - redis_service
    networks:
        - voucher_sys_network

  redis_service:
    image: redis
    container_name: cache
    networks: 
      - voucher_sys_network
    ports:
      - "6379:6379"
networks:
  voucher_sys_network:
    driver: 
      bridge
